# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: en
early_access: true

chat:
  auto_reply: true

reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters: []
  path_instructions: [] # Maybe something for **/**.test.tsx in the future?

  auto_review:
    enabled: true
    ignore_title_keywords: 
      - "WIP"
    labels: []
    drafts: false
    base_branches: 
      - "main"